FROM mcr.microsoft.com/dotnet/core/sdk:3.1 as build
WORKDIR p1/
COPY . .
RUN dotnet build
#RUN dotnet run Images cannot be run from Docker (Because docker is in a container )
RUN dotnet publish -c Release -o out PizzaBox.Client/PizzaBox.Client.csproj
#CMD dotnet /out/PizzaBox.Client.dll

FROM mcr.microsoft.com/dotnet/core/aspnet:3.1

WORKDIR dist/
COPY --from=build p1/out ./
# RUN ls
CMD ["dotnet", "PizzaBox.Client.dll"]
#CMD is executed from outside this container (i.e docker container)

#docker container run -it --rm --name p1 -p 80:8000 pizzabox
#docker image build --file dockerfile --tag pizzabox .

